### ISSUE TITLE
Tests fail on Apple Silicon

### ISSUE THREAD

**Issue by frewsxcv** [georust/proj#52] opened 2020-12-09 22:53 UTC
```
% cargo test
    Finished test [unoptimized + debuginfo] target(s) in 0.08s
     Running target/debug/deps/proj-6a37e3d3cad5067a

running 14 tests
test proj::test::test_definition ... ok
test proj::test::test_conversion_error ... FAILED
test proj::test::test_conversion ... FAILED
test proj::test::test_error_recovery ... FAILED
test proj::test::test_inverse_projection ... FAILED
test proj::test::test_london_inverse ... FAILED
test proj::test::test_searchpath ... ok
test proj::test::test_projection ... FAILED
test proj::test::test_area_of_use ... ok
test proj::test::test_array_convert ... ok
test proj::test::test_from_crs ... FAILED
test proj::test::test_input_order ... FAILED
test proj::test::test_set_endpoint ... ok
proj_create: unrecognized format / unknown name
test proj::test::test_init_error ... ok

failures:

---- proj::test::test_conversion_error stdout ----
thread 'proj::test::test_conversion_error' panicked at 'called `Result::unwrap_err()` on an `Ok` value: MyPoint { x: 0.000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000021451195286, y: 0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000057 }', src/proj.rs:1057:14

---- proj::test::test_conversion stdout ----
thread 'proj::test::test_conversion' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9

---- proj::test::test_error_recovery stdout ----
thread 'proj::test::test_error_recovery' panicked at 'assertion failed: nad83_m.convert(MyPoint::new(0.0, 0.0)).is_ok()', src/proj.rs:1077:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- proj::test::test_inverse_projection stdout ----
thread 'proj::test::test_inverse_projection' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9

---- proj::test::test_london_inverse stdout ----
thread 'proj::test::test_london_inverse' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9

---- proj::test::test_projection stdout ----
thread 'proj::test::test_projection' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9

---- proj::test::test_from_crs stdout ----
thread 'proj::test::test_from_crs' panicked at 'assertion failed: f > 0.99999', src/proj.rs:885:9

---- proj::test::test_input_order stdout ----
thread 'proj::test::test_input_order' panicked at 'assertion failed: `(left == right)`
  left: `6693625.67217475`,
 right: `0.00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000005`', src/proj.rs:1110:9


failures:
    proj::test::test_conversion
    proj::test::test_conversion_error
    proj::test::test_error_recovery
    proj::test::test_from_crs
    proj::test::test_input_order
    proj::test::test_inverse_projection
    proj::test::test_london_inverse
    proj::test::test_projection

test result: FAILED. 6 passed; 8 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.12s

error: test failed, to rerun pass '--lib'
```

**Comment by michaelkirk** [comment] 2021-01-05 21:03
I've reproduced this. Taking a look now.

**Comment by michaelkirk** [comment] 2021-01-05 23:49
I haven't solved this yet, but some notes:

On arm64 mac:

- Reproduced this failure using homebrew proj (7.2.1)
- Reproduced this failure using bundled proj (7.1.0)
  - This first required resolving a "'libtiff' couldn't be found" compiler error. I think this was due to homebrew switching it's root from /usr/local -> /opt/homebrew.
- Successfully built and passed test suite using homebrew proj 7.2.1 on rosetta (x86_64 emulator) and x86_64 toolchain

**Comment by frewsxcv** [comment] 2021-01-17 18:07
I made a minimal reproduction of the issue here: https://github.com/georust/proj/blob/frewsxcv-min/src/main.rs in this draft PR https://github.com/georust/proj/pull/63

I have absolutely no idea what's going on 😔

**Comment by urschrei** [comment] 2021-01-17 19:41
I think we should cast the net wider and see whether the PROJ maintainers (or anyone else in the community) have begun to test on M1, and if they have, whether they can repro this using analogous c or cpp (which I cannot write at all) wrapping the API calls. I just don't see what's wrong on the Rust side.

**Comment by michaelkirk** [comment] 2021-01-17 21:52
I don't currently have access to my M1 machine, but IIRC I was able to build and pass the proj test suite. 

I *think* it was as simple as running `ctest` from the root of the libproj directory, but my memory is fickle.

My best guess was that it had to do with how we were managing pointers, similar to what @urschrei  fixed in #56 but I don't yet have any real evidence or solution.

**Comment by frewsxcv** [comment] 2021-01-21 15:28
This is probably the underlying bug: https://github.com/rust-lang/rust-bindgen/issues/1973

**Comment by frewsxcv** [comment] 2021-01-21 20:44
> This is probably the underlying bug: [rust-lang/rust-bindgen#1973](https://github.com/rust-lang/rust-bindgen/issues/1973)

Confirmed this is the bug. I got tests passing on my Macbook Air M1 with these changes: https://github.com/georust/proj/pull/65

**Closed** 2021-04-19 18:02 UTC
